### ISSUE TITLE
Cannot find Train_Aug.json

### ISSUE THREAD

**Issue by preethiperi** [nimaadmed/WBC_Feature#1]
Hi, I am trying to run your code with the Raabin-WBC dataset but am getting this error:

1:Raabin-WBC  2:LISC  3:BCCD
Please choose one of the above datasets: 1
Traceback (most recent call last):
  File "/Users/preethiperiyakoil/deeplearning/project/WBC_Feature/main.py", line 102, in <module>
    res = results_on_dataset(DATASETS[int(dataset_number)-1])
  File "/Users/preethiperiyakoil/deeplearning/project/WBC_Feature/main.py", line 37, in results_on_dataset
    with open(dataset_folder + folder[:-1] + '.json') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Raabin-WBC/Train.json'

Process finished with exit code 1

Can you please either include your .json files in this repo, or provide code for generating these files based on the double-cropped image directory names? It is not possible to run your code without these .json files.

**Comment by sajadtavakoli** [comment]
Dear Preethiperi, 

You can download the Raabin-wbc data prepared for this repo through the below link:
https://drive.google.com/file/d/1-aPhQyakD79vKYh2l0fPsT2xCiX3UMYi/view?usp=sharing 

Please note that these data are the same as data uploaded on www.Raabindata.com, except these data have been prepared for this repo and the related paper.

**Comment by sajadtavakoli** [comment]
Dear Preethiperi, 

The issue you mentioned has been solved and the repo is ok now. 

Thanks for your report. 

Bests,
